import * as esbuild from 'esbuild';
import { readFileSync, readdirSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { resolve, dirname, basename, join, relative } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = __dirname;

// ---- Step 1: Generate embedded-assets.ts ----
function collectFiles(dir, ext) {
  const result = [];
  if (!existsSync(dir)) return result;
  for (const entry of readdirSync(dir, { recursive: true })) {
    const fullPath = join(dir, entry);
    if (fullPath.endsWith(ext) && !entry.includes('node_modules')) {
      const relPath = relative(ROOT, fullPath).replace(/\\/g, '/');
      const content = readFileSync(fullPath, 'utf-8');
      const varName = relPath.replace(/[^a-zA-Z0-9]/g, '_');
      result.push({ varName, relPath, content });
    }
  }
  return result;
}

const promptFiles = collectFiles(join(ROOT, 'prompts'), '.md');
const templateFiles = collectFiles(join(ROOT, 'templates'), '.md');
const templateIndex = existsSync(join(ROOT, 'templates/index.json'))
  ? JSON.parse(readFileSync(join(ROOT, 'templates/index.json'), 'utf-8'))
  : [];

const allAssets = [...promptFiles, ...templateFiles];

// Generate embedded-assets.ts
let assetsCode = `// Auto-generated by build.mjs - DO NOT EDIT
export interface AssetEntry { path: string; content: string; }

export const embeddedAssets: Record<string, string> = {
`;
for (const f of allAssets) {
  assetsCode += `  ${JSON.stringify(f.relPath)}: ${JSON.stringify(f.content)},\n`;
}
assetsCode += `};

export const templateIndex = ${JSON.stringify(templateIndex, null, 2)};

export function readAsset(path: string): string | null {
  return embeddedAssets[path] || null;
}
`;

const outDir = join(ROOT, 'dist');
if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
const assetsPath = join(ROOT, 'server/src/embedded-assets.ts');
writeFileSync(assetsPath, assetsCode, 'utf-8');
console.log(`Generated: ${assetsPath} (${allAssets.length} assets)`);

// Read API key from .env for build-time injection
const envPath = join(ROOT, 'server/.env');
let apiKey = '';
if (existsSync(envPath)) {
  const envContent = readFileSync(envPath, 'utf-8');
  const match = envContent.match(/DEEPSEEK_API_KEY=(.+)/);
  if (match) apiKey = match[1].trim();
}
console.log(`API key: ${apiKey ? 'found (' + apiKey.slice(0, 8) + '...)' : 'NOT FOUND'}`);

// ---- Step 2: Bundle with esbuild ----
await esbuild.build({
  entryPoints: ['server/src/index.ts'],
  bundle: true,
  platform: 'node',
  target: 'node20',
  format: 'cjs',
  outfile: 'dist/bundle.js',
  sourcemap: false,
  minify: false,
  external: [],
  define: {
    'process.env.NODE_ENV': '"production"',
    'globalThis.BUILD_API_KEY': JSON.stringify(apiKey),
  },
  loader: { '.ts': 'ts' },
  tsconfig: 'server/tsconfig.json',
});

console.log('Bundle created: dist/bundle.js');

// Verify the bundle exists and is reasonable size
const stats = readFileSync('dist/bundle.js', 'utf-8');
console.log(`Bundle size: ${(stats.length / 1024 / 1024).toFixed(2)} MB`);
